<a href="https://colab.research.google.com/github/klnsuman/DataScience/blob/master/TheGrtIndianHackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [2]:
import pandas as pd
import os
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import os
os.chdir('/content/drive/My Drive/Participants_Data_TGIH')

In [5]:
os.listdir()

['Test.csv', 'Sample Submission.csv', 'Train.csv']

In [6]:
df_train = pd.read_csv("Train.csv")
df_test = pd.read_csv("Test.csv")
df_sample = pd.read_csv("Sample Submission.csv")

In [7]:
df_train.shape,df_test.shape,df_sample.shape

((284780, 8), (122049, 7), (122049, 1))

In [8]:
df_train

InvoiceNo  StockCode  Description  ...  UnitPrice CustomerID  Country
0            6141       1583          144  ...       3.75    14056.0       35
1            6349       1300         3682  ...       1.95    13098.0       35
2           16783       2178         1939  ...       5.95    15044.0       35
3           16971       2115         2983  ...       0.83    15525.0       35
4            6080       1210         2886  ...       1.65    13952.0       35
...           ...        ...          ...  ...        ...        ...      ...
284775       3408       1706         1081  ...       1.65    17965.0       35
284776      13982       2184         2947  ...       0.65    16793.0       35
284777       6641        667         3632  ...       8.50    14755.0       35
284778      13820       1576         3089  ...       3.45    14866.0       35
284779      11042       2603         1156  ...       0.75    17585.0       35

[284780 rows x 8 columns]

In [9]:
df_train[['Quantity','UnitPrice']]

Quantity  UnitPrice
0              3       3.75
1              6       1.95
2              4       5.95
3              1       0.83
4             12       1.65
...          ...        ...
284775         6       1.65
284776        16       0.65
284777         4       8.50
284778        48       3.45
284779         2       0.75

[284780 rows x 2 columns]

### 1. **Single Variate**

In [10]:
from sklearn.model_selection import train_test_split

X = df_train.iloc[:,3:4].values
Y = df_train.iloc[:,5:6].values

## Split into Test and Training Set

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=1/3,random_state=0)


In [11]:
X.shape,Y.shape,X_train.shape,Y_train.shape

((284780, 1), (284780, 1), (189853, 1), (189853, 1))

In [12]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
print("Mode Coeff or Slope ",model.coef_)
print("Mode Coeff or Slope ",model.intercept_)

Mode Coeff or Slope  [[-0.00031093]]
Mode Coeff or Slope  [3.49470048]


In [14]:
Y_predict = model.predict(X_test)

In [15]:
from sklearn.metrics import mean_squared_error,r2_score
print("mean squared error ",mean_squared_error(Y_test,Y_predict))

mean squared error  852.6480200241125


In [16]:
print('Variance score = %.2f' % r2_score(Y_test, Y_predict))

Variance score = -0.00


In [17]:
np.hstack((Y_test, Y_predict))

array([[2.08      , 3.48226321],
       [0.42      , 3.48692719],
       [1.25      , 3.49345676],
       ...,
       [1.65      , 3.49407862],
       [9.95      , 3.49438955],
       [2.95      , 3.49407862]])

### 2. **Multi Variate**

In [18]:
df_train.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [19]:
df_train.Country.value_counts(sort=False)

0        883
1        303
2         10
3       1435
4         20
5        106
6        537
7        424
8         26
9        273
10      5244
11        40
12       489
13      5946
14      6653
15       101
16       132
17       185
18       561
19       238
20        34
21        25
22        89
23      1680
24       766
25       244
26      1049
27        47
28         8
29       152
30      1776
31       325
32      1293
33       210
34        52
35    253253
36       171
Name: Country, dtype: int64

In [20]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284780 entries, 0 to 284779
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    284780 non-null  int64  
 1   StockCode    284780 non-null  int64  
 2   Description  284780 non-null  int64  
 3   Quantity     284780 non-null  int64  
 4   InvoiceDate  284780 non-null  object 
 5   UnitPrice    284780 non-null  float64
 6   CustomerID   284780 non-null  float64
 7   Country      284780 non-null  int64  
dtypes: float64(2), int64(5), object(1)
memory usage: 17.4+ MB


In [21]:
df_m_train = pd.read_csv("Train.csv")
df_m_test = pd.read_csv("Test.csv")
df_m_sample = pd.read_csv("Sample Submission.csv")


In [22]:

features = ['InvoiceNo','Description','CustomerID']
df_m = df_m_train.drop(features, axis=1, inplace=False)

In [23]:
t = df_m[['StockCode','Quantity','Country']]
t1 = df_m[['UnitPrice']]

In [24]:
t1

UnitPrice
0            3.75
1            1.95
2            5.95
3            0.83
4            1.65
...           ...
284775       1.65
284776       0.65
284777       8.50
284778       3.45
284779       0.75

[284780 rows x 1 columns]

In [25]:
X = t.iloc[:,:].values
Y = df_m.iloc[:,3:4].values

In [26]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=1/3,random_state=0)

In [27]:
X_train

array([[ 617,   12,   35],
       [3388,    2,    3],
       [2785,    4,   35],
       ...,
       [1047,    2,   35],
       [1660,    6,   35],
       [ 878,    4,   35]])

In [28]:
from sklearn.linear_model import LinearRegression

model = LinearRegression(normalize=True)
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [29]:
print("Mode Coeff or Slope ",model.coef_)
print("Mode Coeff or Slope ",model.intercept_)

Mode Coeff or Slope  [[ 0.00201133 -0.00031669 -0.05585275]]
Mode Coeff or Slope  [2.16258926]


In [30]:
from sklearn.metrics import mean_squared_error,r2_score
print("mean squared error ",mean_squared_error(Y_test,Y_predict))

mean squared error  852.6480200241125


In [31]:
print('Variance score = %.2f' % r2_score(Y_test, Y_predict))

Variance score = -0.00


In [32]:
Y_test , Y_predict

(array([[2.08],
        [0.42],
        [1.25],
        ...,
        [1.65],
        [9.95],
        [2.95]]), array([[3.48226321],
        [3.48692719],
        [3.49345676],
        ...,
        [3.49407862],
        [3.49438955],
        [3.49407862]]))

In [33]:
np.hstack((Y_test, Y_predict))

array([[2.08      , 3.48226321],
       [0.42      , 3.48692719],
       [1.25      , 3.49345676],
       ...,
       [1.65      , 3.49407862],
       [9.95      , 3.49438955],
       [2.95      , 3.49407862]])

In [34]:
print(df_train.apply(lambda x : sum(x.isnull())))

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64


In [35]:
#(df_train.groupby('StockCode')['UnitPrice'].min(),df_train.groupby('StockCode')['UnitPrice'].count())

functions = ['count','min','max','sum','mean','std']
df_train.groupby(df_train['StockCode'])['UnitPrice'].agg(functions)


count    min        max         sum        mean          std
StockCode                                                              
0             32   0.85      0.850      27.200    0.850000     0.000000
1             14   0.39      0.850       5.920    0.422857     0.122940
2             23   0.21      0.210       4.830    0.210000     0.000000
3              3   0.65      0.650       1.950    0.650000     0.000000
4              4   0.42      0.420       1.680    0.420000     0.000000
...          ...    ...        ...         ...         ...          ...
3679          49   0.01   1867.860    4292.730   87.606735   268.936159
3680          14  11.17   1599.260   10942.230  781.587857   548.848549
3681         320   0.00  38970.000  107096.470  334.676469  2254.157390
3682           4   0.00      0.001       0.003    0.000750     0.000500
3683         840   1.00   8142.750   27902.050   33.216726   282.305604

[3619 rows x 6 columns]

In [36]:
df_train["Date"]= pd.to_datetime(df_train["InvoiceDate"]) 
functions = ['count','min','max']
df_train.groupby(df_train['StockCode'])['Date'].agg(functions)

count                 min                 max
StockCode                                               
0             32 2010-12-01 08:45:00 2011-04-18 12:56:00
1             14 2011-02-27 13:47:00 2011-11-21 17:04:00
2             23 2010-12-03 14:54:00 2011-12-04 13:15:00
3              3 2010-12-03 11:19:00 2011-03-31 13:14:00
4              4 2010-12-06 13:13:00 2011-11-06 13:00:00
...          ...                 ...                 ...
3679          49 2010-12-01 09:41:00 2011-12-01 08:49:00
3680          14 2011-08-30 10:49:00 2011-12-05 17:17:00
3681         320 2010-12-01 15:35:00 2011-12-09 10:28:00
3682           4 2011-04-15 09:27:00 2011-09-25 14:58:00
3683         840 2010-12-01 08:45:00 2011-12-09 12:16:00

[3619 rows x 3 columns]

In [37]:
df_train

InvoiceNo  StockCode  ...  Country                Date
0            6141       1583  ...       35 2011-05-06 16:54:00
1            6349       1300  ...       35 2011-05-11 07:35:00
2           16783       2178  ...       35 2011-11-20 13:20:00
3           16971       2115  ...       35 2011-11-22 12:07:00
4            6080       1210  ...       35 2011-05-06 09:00:00
...           ...        ...  ...      ...                 ...
284775       3408       1706  ...       35 2011-03-01 12:07:00
284776      13982       2184  ...       35 2011-10-13 15:08:00
284777       6641        667  ...       35 2011-05-16 12:59:00
284778      13820       1576  ...       35 2011-10-11 14:18:00
284779      11042       2603  ...       35 2011-08-22 13:30:00

[284780 rows x 9 columns]

In [38]:
df_train.groupby('StockCode')['UnitPrice'].describe().unstack()

       StockCode
count  0               32.000
       1               14.000
       2               23.000
       3                3.000
       4                4.000
                      ...    
max    3679          1867.860
       3680          1599.260
       3681         38970.000
       3682             0.001
       3683          8142.750
Length: 28952, dtype: float64

In [39]:
df_train.StockCode.nunique()

3619

In [40]:
np.hstack((Y_test, Y_predict))

array([[2.08      , 3.48226321],
       [0.42      , 3.48692719],
       [1.25      , 3.49345676],
       ...,
       [1.65      , 3.49407862],
       [9.95      , 3.49438955],
       [2.95      , 3.49407862]])

In [41]:
df_train["Date"].head()

0   2011-05-06 16:54:00
1   2011-05-11 07:35:00
2   2011-11-20 13:20:00
3   2011-11-22 12:07:00
4   2011-05-06 09:00:00
Name: Date, dtype: datetime64[ns]

In [42]:
df_train[df_train["StockCode"] == 3679]['UnitPrice'].describe()[2]

268.9361587609885

In [43]:
df_train[df_train["StockCode"] == 3679].sort_values(by="Date")

InvoiceNo  StockCode  ...  Country                Date
277448      18536       3679  ...       35 2010-12-01 09:41:00
222039      18735       3679  ...       35 2010-12-15 09:14:00
39161       18740       3679  ...       35 2010-12-15 12:35:00
138744      18859       3679  ...       35 2011-01-05 12:26:00
178214      19175       3679  ...       35 2011-02-11 14:12:00
272363      19179       3679  ...       35 2011-02-11 15:07:00
30399       19201       3679  ...       35 2011-02-11 17:10:00
133258      19214       3679  ...       35 2011-02-14 11:19:00
238886      19323       3679  ...       35 2011-03-03 11:05:00
249645      19324       3679  ...       35 2011-03-03 11:08:00
44967       19391       3679  ...       35 2011-03-09 12:21:00
79965       19574       3679  ...       35 2011-03-31 10:36:00
111768      19579       3679  ...       35 2011-03-31 12:11:00
65239       19659       3679  ...       35 2011-04-08 14:17:00
90323       19805       3679  ...       35 2011-04-27 10:22:00
175352      19908       3679  ...       35 2011-05-10 14:03:00
243757      19986       3679  ...       35 2011-05-18 12:16:00
163673      19995       3679  ...       35 2011-05-19 12:19:00
161800      20059       3679  ...       35 2011-05-24 16:50:00
178648      20181       3679  ...       35 2011-06-06 10:19:00
54876       20217       3679  ...       35 2011-06-09 19:24:00
70451       20275       3679  ...       35 2011-06-14 14:40:00
250361      20278       3679  ...       35 2011-06-15 12:00:00
168785      20543       3679  ...       35 2011-07-14 12:30:00
283799      20612       3679  ...       35 2011-07-21 12:25:00
113016      20616       3679  ...       35 2011-07-21 14:32:00
237291      20651       3679  ...       35 2011-07-26 10:06:00
191803      20668       3679  ...       35 2011-07-27 12:40:00
32504       20816       3679  ...       10 2011-08-14 14:35:00
155357      20905       3679  ...       35 2011-08-25 14:07:00
109457      20922       3679  ...       35 2011-08-30 11:45:00
46801       20922       3679  ...       35 2011-08-30 11:45:00
5962        20932       3679  ...       35 2011-08-31 12:29:00
248034      20960       3679  ...       35 2011-08-31 17:25:00
87552       20962       3679  ...       35 2011-08-31 17:45:00
39597       20974       3679  ...       35 2011-09-02 12:41:00
109323      20978       3679  ...       35 2011-09-02 16:23:00
6028        21062       3679  ...       35 2011-09-13 17:28:00
139369      21179       3679  ...       35 2011-09-22 15:59:00
153199      21316       3679  ...       35 2011-10-06 12:37:00
47649       21653       3679  ...       35 2011-11-03 12:39:00
47528       21653       3679  ...       35 2011-11-03 12:39:00
213050      21798       3679  ...       35 2011-11-11 12:52:00
49217       21814       3679  ...       35 2011-11-14 12:57:00
236542      21827       3679  ...       35 2011-11-14 13:40:00
28547       21887       3679  ...       35 2011-11-18 12:06:00
134392      21887       3679  ...       35 2011-11-18 12:06:00
236650      22044       3679  ...       35 2011-11-30 17:34:00
41125       22062       3679  ...       35 2011-12-01 08:49:00

[49 rows x 9 columns]

In [44]:
df_train["DateDiff"] = df_train[df_train["StockCode"] == 3679]["Date"].min()

Timestamp('2010-12-01 09:41:00')