In [2]:
import math
import numpy as np

###    Haversine Distance 
<br>
Get the Distance between the Two points on earths surface.
The location of point is given by latitude and longitude points.

(1) Haversine formula:
    <br>
        a = sin²(Δφ/2) + cos φ1 * cos φ2 * sin²(Δλ/2)
        <br>
        c = 2 * atan2( √a, √(1−a) )
        <br>
        d = R * c 
        <br>
where φ is latitude, λ is longitude, R is earth’s radius (mean radius = 6,371km);
<br>
note that angles need to be in radians to pass to trig functions!

In [3]:
def haversineFunction(latitude1,longitude1,latitude2,longitude2):
    
    R = 6371   
    
    lat1_rad = math.radians(latitude1)
    lat2_rad = math.radians(latitude2)
    
    lon1_rad = math.radians(longitude1)
    lon2_rad = math.radians(longitude2)
   
    deltaLat = (lat2_rad - lat1_rad)
    deltaLon = (lon2_rad - lon1_rad)
   
  
    a = math.sin(deltaLat/2) * math.sin(deltaLat/2)+ math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(deltaLon/2)*math.sin(deltaLon/2)
    c = 2 * math.atan2(math.sqrt(a),math.sqrt(1-a))
     
    d = R * c
     
    return d
    
    
    

#### Latititude and Longitudes
<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br>
<table style="width:50%">
  <tr>
    <th>City</th>
    <th>Latitude</th>
    <th>Longutude</th>
  </tr>
  <tr>
    <td>Panaji</td>
    <td>15.4909N</td>
    <td>73.8278E</td>
  </tr>
  <tr>
    <td>Raichur</td>
    <td>16.2076N</td>
    <td>77.3463E</td>
  </tr>
 <tr>
    <td>Mangalore</td>
    <td>12.9141N</td>
    <td>74.8560E</td>
  </tr>
 <tr>
    <td>Bellari</td>
    <td>15.1394N</td>
    <td>76.9214E</td>
  </tr>
 <tr>
    <td>Tirupati</td>
    <td>13.6288N</td>
    <td>79.4192E</td>
  </tr>
 <tr>
    <td>Kurnool</td>
    <td>15.8281N</td>
    <td>78.0373E</td>
  </tr> 
  <tr>
    <td>Kozhikode</td>
    <td>11.2588N</td>
    <td>75.7804E</td>
  </tr>
 <tr>
    <td>Banglore</td>
    <td>12.9716N</td>
    <td>77.5946E</td>
  </tr>
 <tr>
    <td>Nellore</td>
    <td>14.4426N</td>
    <td>79.9865E</td>
  </tr>
 <tr>
    <td>Chennai</td>
    <td>13.0827N</td>
    <td>82.2707E</td>
  </tr>
</table> 

In [4]:
haversineFunction(15.4909,73.8278,13.0827,80.2707)

744.0351557019156

In [5]:
cities = {0 : {'name':'Panaji'      ,'latitude':15.4909,'longitude':73.8278},
          1 : {'name':'Raichur'     ,'latitude':16.2076,'longitude':77.3463},
          2 : {'name':'Mangalore'   ,'latitude':12.9141,'longitude':74.8560},
          3 : {'name':'Bellari'     ,'latitude':15.1394,'longitude':76.9214},
          4 : {'name':'Tirupati'    ,'latitude':13.6288,'longitude':79.4192},
          5 : {'name':'Kurnool'     ,'latitude':15.8281,'longitude':78.0373},
          6 : {'name':'Kozhikode'   ,'latitude':11.2588,'longitude':75.7804},
          7 : {'name':'Bangalore'   ,'latitude':12.9716,'longitude':77.5946},
          8 : {'name':'Nellore'     ,'latitude':14.4426,'longitude':79.9865},
          9 : {'name':'Chennai'     ,'latitude':13.0827,'longitude':80.2707}
         }

In [6]:
print(cities)

{0: {'name': 'Panaji', 'latitude': 15.4909, 'longitude': 73.8278}, 1: {'name': 'Raichur', 'latitude': 16.2076, 'longitude': 77.3463}, 2: {'name': 'Mangalore', 'latitude': 12.9141, 'longitude': 74.856}, 3: {'name': 'Bellari', 'latitude': 15.1394, 'longitude': 76.9214}, 4: {'name': 'Tirupati', 'latitude': 13.6288, 'longitude': 79.4192}, 5: {'name': 'Kurnool', 'latitude': 15.8281, 'longitude': 78.0373}, 6: {'name': 'Kozhikode', 'latitude': 11.2588, 'longitude': 75.7804}, 7: {'name': 'Bangalore', 'latitude': 12.9716, 'longitude': 77.5946}, 8: {'name': 'Nellore', 'latitude': 14.4426, 'longitude': 79.9865}, 9: {'name': 'Chennai', 'latitude': 13.0827, 'longitude': 80.2707}}


In [7]:
dest_lat,dest_lon = cities[9]['latitude'],cities[9]['longitude']

for i in range(10):
    source_lat,source_lon = cities[i]['latitude'],cities[i]['longitude']
    cities[i]['heuristic_cost'] = haversineFunction(source_lat,source_lon,dest_lat,dest_lon)
    

In [8]:
print(cities)

{0: {'name': 'Panaji', 'latitude': 15.4909, 'longitude': 73.8278, 'heuristic_cost': 744.0351557019156}, 1: {'name': 'Raichur', 'latitude': 16.2076, 'longitude': 77.3463, 'heuristic_cost': 468.7090788152219}, 2: {'name': 'Mangalore', 'latitude': 12.9141, 'longitude': 74.856, 'heuristic_cost': 586.9476757845566}, 3: {'name': 'Bellari', 'latitude': 15.1394, 'longitude': 76.9214, 'heuristic_cost': 427.4793247479098}, 4: {'name': 'Tirupati', 'latitude': 13.6288, 'longitude': 79.4192, 'heuristic_cost': 110.33441493944744}, 5: {'name': 'Kurnool', 'latitude': 15.8281, 'longitude': 78.0373, 'heuristic_cost': 388.599828847867}, 6: {'name': 'Kozhikode', 'latitude': 11.2588, 'longitude': 75.7804, 'heuristic_cost': 528.508520052874}, 7: {'name': 'Bangalore', 'latitude': 12.9716, 'longitude': 77.5946, 'heuristic_cost': 290.1720249530604}, 8: {'name': 'Nellore', 'latitude': 14.4426, 'longitude': 79.9865, 'heuristic_cost': 154.2976211368278}, 9: {'name': 'Chennai', 'latitude': 13.0827, 'longitude': 80

In [9]:
 adjacency_matrix = np.zeros([10, 10],dtype=int)

In [10]:
print(adjacency_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [11]:
print(adjacency_matrix[0][0])

0


In [12]:
def create_route_graph(vertex_a,vertex_b,cost,cities):
    for city_idx, city_info in cities.items():
        if(cities[city_idx]['name'] == vertex_a):
            source_idx = city_idx
        if(cities[city_idx]['name'] == vertex_b):
            dest_idx = city_idx    
    
    adjacency_matrix[source_idx][dest_idx] = cost
    adjacency_matrix[dest_idx][source_idx] = cost
    

### --------------------------------------------------------------------------
    Create Graph using dictionary
    <br>
    Create Routes with Costs 
    <br>
    Create and Populate the Adjacency Matric with Costs between cities
### --------------------------------------------------------------------------

In [13]:
create_route_graph('Panaji','Mangalore',365,cities)
create_route_graph('Panaji','Raichur',457,cities)
create_route_graph('Panaji','Bellari',409,cities)
create_route_graph('Raichur','Tirupati',453,cities)
create_route_graph('Raichur','Kurnool',100,cities)
create_route_graph('Tirupati','Bellari',379,cities)
create_route_graph('Tirupati','Kurnool',340,cities)
create_route_graph('Tirupati','Nellore',136,cities)
create_route_graph('Tirupati','Chennai',153,cities)
create_route_graph('Kurnool','Nellore',325,cities)
create_route_graph('Bellari','Bangalore',311,cities)
create_route_graph('Bangalore','Mangalore',352,cities)
create_route_graph('Bangalore','Kozhikode',356,cities)
create_route_graph('Chennai','Bangalore',346,cities)
create_route_graph('Nellore','Chennai',175,cities)
create_route_graph('Mangalore','Kozhikode',233,cities)

In [14]:
print(adjacency_matrix)

[[  0 457 365 409   0   0   0   0   0   0]
 [457   0   0   0 453 100   0   0   0   0]
 [365   0   0   0   0   0 233 352   0   0]
 [409   0   0   0 379   0   0 311   0   0]
 [  0 453   0 379   0 340   0   0 136 153]
 [  0 100   0   0 340   0   0   0 325   0]
 [  0   0 233   0   0   0   0 356   0   0]
 [  0   0 352 311   0   0 356   0   0 346]
 [  0   0   0   0 136 325   0   0   0 175]
 [  0   0   0   0 153   0   0 346 175   0]]


###  ----------------------------------------------------------------------------------------
<br>
Using Prority Queue to sort the cities based on Evaluation Function.
<br>
Evaluation_Function = Cost_to_reach_the_node + Heristic_function_cost_Haversine_Cost_function
<br>
Create class to Hold the PriorityQueue Based on the Evaluation Function
<br>
__lt__ is a construction which overrides the "<". 
<br>
When "<" is used to compare , the EvaluationFunction Values are compared.
<br>

###  ----------------------------------------------------------------------------------------

In [15]:
class PriorityQueue:
    class _city_eval_item:
        def __init__(self,cityName,evalFunctionCost):
            self._cityName = cityName
            self._evalFunctionCost = evalFunctionCost
        def __lt__(self,other):
            #print("Base self._cityName->",self._cityName)
            #print("Base self._evalFunctionCost->",self._evalFunctionCost)
            #print("Base other._cityName->",other._cityName)
            #print("Base other._evalFunctionCost->",other._evalFunctionCost)
            return self._evalFunctionCost < other._evalFunctionCost
    
    def add(self,cityName,evalFunctionCost):
        return NotImplementedError("Must be Implemented by subclass")
    
    def isEmpty(self):
        return len(self) == 0
    
    def __len__(self):
        return NotImplementedError("Must be Implemented by subclass")
    
    def min(self):
        return NotImplementedError("Must be Implemented by subclass")
    
    def remove_min(self):
        return NotImplementedError("Must be Implemented by subclass")
    

### -------------------------------------------------------------------

Create a HeapSort , which sorts based on the Evaluation Function
    
### -------------------------------------------------------------------

In [16]:
class HeapSort(PriorityQueue):
 
    # ---------------- Private Methods -----------------------
    def _parent(self,j):
        #print("j=>",j,"parent=>",(j-1)//2)
        return (j-1)//2
    
    def _left(self,j):
        return 2*j + 1
    
    def _right(self,j):
        return 2*j + 2
    
    def _hasleft(self,j):
        return self._left(j) < len(self._array)
    
    def _hasright(self,j):
        return self._right(j) < len(self._array)
    
    def _swap(self,i,j):
        #print("Swap ",i," with ",j)
        self._array[i], self._array[j] = self._array[j], self._array[i]
    
    def _upheap(self,j):
        
        parent = self._parent(j)
        if(j>0 and self._array[j] < self._array[parent]):
            self._swap(j,parent)
            self._upheap(parent)
    
    def _downheap(self,j):
        
        if self._hasleft(j):
            left = self._left(j)
            small = left
           
            if(self._hasright(j)):
                right = self._right(j)
                if(self._array[right] < self._array[left]):
                    small = right
                   
            if(self._array[small] < self._array[j]):
               
                #print("j",j,small) 
                self._swap(j,small) 
                self._downheap(small)


    
    # ---------------- Private Methods -----------------------   
    def __init__(self):
        self._array = []
    
    
    def __len__(self):
        return len(self._array)
    
    def add(self,key,value):
        self._array.append(self._city_eval_item(key,value))
        self._upheap(len(self._array)-1)
        
    def getMin(self):
        
        if self.isEmpty():
            raise NotImplementedError('The Array is Empty ')
        item = self._array[0]     
        return (item._cityName,item._evalFunctionCost)

   
    def extractMin(self):
        
        if(len(self._array) == 0):
            return NotImplementedError('The Array is Empty')
        
        self._swap(0,len(self._array)-1)
        item = self._array.pop()
        self._downheap(0)
        return (item._cityName,item._evalFunctionCost)
    
    def print(self):
        print("len(self._array)=>",len(self._array))
        for i in range(len(self._array)):
            item = self._array[i]  
            print(item._cityName,item._evalFunctionCost)   

In [17]:
print(cities)

{0: {'name': 'Panaji', 'latitude': 15.4909, 'longitude': 73.8278, 'heuristic_cost': 744.0351557019156}, 1: {'name': 'Raichur', 'latitude': 16.2076, 'longitude': 77.3463, 'heuristic_cost': 468.7090788152219}, 2: {'name': 'Mangalore', 'latitude': 12.9141, 'longitude': 74.856, 'heuristic_cost': 586.9476757845566}, 3: {'name': 'Bellari', 'latitude': 15.1394, 'longitude': 76.9214, 'heuristic_cost': 427.4793247479098}, 4: {'name': 'Tirupati', 'latitude': 13.6288, 'longitude': 79.4192, 'heuristic_cost': 110.33441493944744}, 5: {'name': 'Kurnool', 'latitude': 15.8281, 'longitude': 78.0373, 'heuristic_cost': 388.599828847867}, 6: {'name': 'Kozhikode', 'latitude': 11.2588, 'longitude': 75.7804, 'heuristic_cost': 528.508520052874}, 7: {'name': 'Bangalore', 'latitude': 12.9716, 'longitude': 77.5946, 'heuristic_cost': 290.1720249530604}, 8: {'name': 'Nellore', 'latitude': 14.4426, 'longitude': 79.9865, 'heuristic_cost': 154.2976211368278}, 9: {'name': 'Chennai', 'latitude': 13.0827, 'longitude': 80

In [19]:
hs = HeapSort()


In [20]:
print(adjacency_matrix)

[[  0 457 365 409   0   0   0   0   0   0]
 [457   0   0   0 453 100   0   0   0   0]
 [365   0   0   0   0   0 233 352   0   0]
 [409   0   0   0 379   0   0 311   0   0]
 [  0 453   0 379   0 340   0   0 136 153]
 [  0 100   0   0 340   0   0   0 325   0]
 [  0   0 233   0   0   0   0 356   0   0]
 [  0   0 352 311   0   0 356   0   0 346]
 [  0   0   0   0 136 325   0   0   0 175]
 [  0   0   0   0 153   0   0 346 175   0]]


In [21]:
print(hs.print())

len(self._array)=> 0
None


In [31]:
start_idx = 0
op_route = np.zeros([10],dtype=int)
i=0
j=0
path = {0 :{'city':cities[0]['name'],'cost':cities[0]['heuristic_cost']+0}}
running_cost = 0
frontier = {}
frontier[0] = {}
frontier[0]['name'] = 'Panaji'
frontier[0]['cost'] = 0 + cities[0]['heuristic_cost']
CLOSED_LIST = 0
op_route[0] = 0
j=j+1
while (start_idx <=9 ):
    i = start_idx
    if(start_idx < 9):
        while (i<=9):
            route_cost = adjacency_matrix[start_idx][i] 
            if(route_cost>0):
                evalCost = route_cost + cities[i]['heuristic_cost']
                #print(evalCost)
                hs.add(i,evalCost)
               
                
            i = i+1
       
        print(hs.print())
        if(len(hs)<=0):
            start_idx = 10
        else:
            item = hs.extractMin()   
            print("Min",item[0] , item[1])
            op_route[j]= item[0]
            k = item[0]
            frontier[k] = {}
            frontier[k]['name'] = cities[k]['name']
            frontier[k]['cost'] = evalCost
            j=j+1
            start_idx = item[0]
    else:
        start_idx = 10
print(frontier)
print("op_route",op_route," j",j)
for i in range(j):
    k = op_route[i]
    print(cities[k]['name'],cities[k]['heuristic_cost'],end="->")
print("path:",path)
hs  = HeapSort()

len(self._array)=> 3
3 836.4793247479098
2 951.9476757845566
1 925.7090788152219
None
Min 3 836.4793247479098
len(self._array)=> 4
4 489.33441493944747
7 601.1720249530604
1 925.7090788152219
2 951.9476757845566
None
Min 4 489.33441493944747
len(self._array)=> 6
9 153.0
7 601.1720249530604
8 290.2976211368278
2 951.9476757845566
5 728.599828847867
1 925.7090788152219
None
Min 9 153.0
{0: {'name': 'Panaji', 'cost': 744.0351557019156}, 3: {'name': 'Bellari', 'cost': 836.4793247479098}, 4: {'name': 'Tirupati', 'cost': 601.1720249530604}, 9: {'name': 'Chennai', 'cost': 153.0}}
op_route [0 3 4 9 0 0 0 0 0 0]  j 4
Panaji 744.0351557019156->Bellari 427.4793247479098->Tirupati 110.33441493944744->Chennai 0.0->path: {0: {'city': 'Panaji', 'cost': 744.0351557019156}}


In [ ]:
hs.print()