In [55]:
import math
import numpy as np

###    Haversine Distance 
<br>
Get the Distance between the Two points on earths surface.
The location of point is given by latitude and longitude points.

(1) Haversine formula:
    <br>
        a = sin²(Δφ/2) + cos φ1 * cos φ2 * sin²(Δλ/2)
        <br>
        c = 2 * atan2( √a, √(1−a) )
        <br>
        d = R * c 
        <br>
where φ is latitude, λ is longitude, R is earth’s radius (mean radius = 6,371km);
<br>
note that angles need to be in radians to pass to trig functions!

In [56]:
def haversineFunction(latitude1,longitude1,latitude2,longitude2):
    
    R = 6371e3   ## Metres
    
    lat1_rad = math.radians(latitude1)
    lat2_rad = math.radians(latitude2)
    
    lon1_rad = math.radians(longitude1)
    lon2_rad = math.radians(longitude2)
    
    deltaLat = math.radians(lat2_rad - lat1_rad)
    deltaLon = math.radians(lon2_rad - lon2_rad)
     
    a = math.sin(deltaLat/2) * math.sin(deltaLat/2)+ math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(deltaLon/2)*math.sin(deltaLon/2)
    c = 2 * math.atan2(math.sqrt(a),math.sqrt(1-a))
    
    d = R * c
    
    print(d)
    
    return d
    
    
    

#### Latititude and Longitudes
<style>
table, th, td {
  border: 1px solid black;
}
</style>
<br>
<table style="width:50%">
  <tr>
    <th>City</th>
    <th>Latitude</th>
    <th>Longutude</th>
  </tr>
  <tr>
    <td>Panaji</td>
    <td>15.4909N</td>
    <td>73.8278E</td>
  </tr>
  <tr>
    <td>Raichur</td>
    <td>16.2076N</td>
    <td>77.3463E</td>
  </tr>
 <tr>
    <td>Mangalore</td>
    <td>12.9141N</td>
    <td>74.8560E</td>
  </tr>
 <tr>
    <td>Bellari</td>
    <td>15.1394N</td>
    <td>76.9214E</td>
  </tr>
 <tr>
    <td>Tirupati</td>
    <td>13.6288N</td>
    <td>79.4192E</td>
  </tr>
 <tr>
    <td>Kurnool</td>
    <td>15.8281N</td>
    <td>78.0373E</td>
  </tr> 
  <tr>
    <td>Kozhikode</td>
    <td>11.2588N</td>
    <td>75.7804E</td>
  </tr>
 <tr>
    <td>Banglore</td>
    <td>12.9716N</td>
    <td>77.5946E</td>
  </tr>
 <tr>
    <td>Nellore</td>
    <td>14.4426N</td>
    <td>79.9865E</td>
  </tr>
 <tr>
    <td>Chennai</td>
    <td>13.0827N</td>
    <td>82.2707E</td>
  </tr>
</table> 

In [57]:
haversineFunction(15.4909,73.8278,13.0827,80.2707)

4673.636079674668


4673.636079674668

In [78]:
cities = {0 : {'name':'Panaji'      ,'latitude':15.4909,'longitude':73.8278},
          1 : {'name':'Raichur'     ,'latitude':16.2076,'longitude':77.3463},
          2 : {'name':'Mangalore'   ,'latitude':12.9141,'longitude':74.8560},
          3 : {'name':'Bellari'     ,'latitude':15.1394,'longitude':76.9214},
          4 : {'name':'Tirupati'    ,'latitude':13.6288,'longitude':79.4192},
          5 : {'name':'Kurnool'     ,'latitude':15.8281,'longitude':78.0373},
          6 : {'name':'Kozhikode'   ,'latitude':11.2588,'longitude':75.7804},
          7 : {'name':'Bangalore'   ,'latitude':12.9716,'longitude':77.5946},
          8 : {'name':'Nellore'     ,'latitude':14.4426,'longitude':79.9865},
          9 : {'name':'Chennai'     ,'latitude':13.0827,'longitude':82.2707}
         }

In [79]:
print(cities)

{0: {'name': 'Panaji', 'latitude': 15.4909, 'longitude': 73.8278}, 1: {'name': 'Raichur', 'latitude': 16.2076, 'longitude': 77.3463}, 2: {'name': 'Mangalore', 'latitude': 12.9141, 'longitude': 74.856}, 3: {'name': 'Bellari', 'latitude': 15.1394, 'longitude': 76.9214}, 4: {'name': 'Tirupati', 'latitude': 13.6288, 'longitude': 79.4192}, 5: {'name': 'Kurnool', 'latitude': 15.8281, 'longitude': 78.0373}, 6: {'name': 'Kozhikode', 'latitude': 11.2588, 'longitude': 75.7804}, 7: {'name': 'Bangalore', 'latitude': 12.9716, 'longitude': 77.5946}, 8: {'name': 'Nellore', 'latitude': 14.4426, 'longitude': 79.9865}, 9: {'name': 'Chennai', 'latitude': 13.0827, 'longitude': 82.2707}}


In [84]:
dest_lat,dest_lon = cities[9]['latitude'],cities[9]['longitude']

for i in range(10):
    source_lat,source_lon = cities[i]['latitude'],cities[i]['longitude']
    cities[i]['heuristic_cost'] = haversineFunction(source_lat,source_lon,dest_lat,dest_lon)
    

4673.636079674668
6064.548370307855
327.2049842343463
3991.4738497910853
1059.825871235917
5328.046048143355
3539.674796826936
215.61372330032958
2639.181839028975
0.0


In [85]:
print(cities)

{0: {'name': 'Panaji', 'latitude': 15.4909, 'longitude': 73.8278, 'heuristic_cost': 4673.636079674668}, 1: {'name': 'Raichur', 'latitude': 16.2076, 'longitude': 77.3463, 'heuristic_cost': 6064.548370307855}, 2: {'name': 'Mangalore', 'latitude': 12.9141, 'longitude': 74.856, 'heuristic_cost': 327.2049842343463}, 3: {'name': 'Bellari', 'latitude': 15.1394, 'longitude': 76.9214, 'heuristic_cost': 3991.4738497910853}, 4: {'name': 'Tirupati', 'latitude': 13.6288, 'longitude': 79.4192, 'heuristic_cost': 1059.825871235917}, 5: {'name': 'Kurnool', 'latitude': 15.8281, 'longitude': 78.0373, 'heuristic_cost': 5328.046048143355}, 6: {'name': 'Kozhikode', 'latitude': 11.2588, 'longitude': 75.7804, 'heuristic_cost': 3539.674796826936}, 7: {'name': 'Bangalore', 'latitude': 12.9716, 'longitude': 77.5946, 'heuristic_cost': 215.61372330032958}, 8: {'name': 'Nellore', 'latitude': 14.4426, 'longitude': 79.9865, 'heuristic_cost': 2639.181839028975}, 9: {'name': 'Chennai', 'latitude': 13.0827, 'longitude':

In [86]:
 adjacency_matrix = np.zeros([10, 10],dtype=int)

In [87]:
print(adjacency_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [88]:
print(adjacency_matrix[0][0])

0


In [89]:
def create_route_graph(vertex_a,vertex_b,cost,cities):
    for city_idx, city_info in cities.items():
        if(cities[city_idx]['name'] == vertex_a):
            source_idx = city_idx
        if(cities[city_idx]['name'] == vertex_b):
            dest_idx = city_idx    
    
    adjacency_matrix[source_idx][dest_idx] = cost
    adjacency_matrix[dest_idx][source_idx] = cost
    

In [92]:
create_route_graph('Panaji','Mangalore',365,cities)
create_route_graph('Panaji','Raichur',457,cities)
create_route_graph('Panaji','Bellari',409,cities)
create_route_graph('Raichur','Tirupati',453,cities)
create_route_graph('Raichur','Kurnool',100,cities)
create_route_graph('Tirupati','Bellari',379,cities)
create_route_graph('Tirupati','Kurnool',340,cities)
create_route_graph('Tirupati','Nellore',136,cities)
create_route_graph('Tirupati','Chennai',153,cities)
create_route_graph('Kurnool','Nellore',325,cities)
create_route_graph('Bellari','Bangalore',311,cities)
create_route_graph('Bangalore','Mangalore',352,cities)
create_route_graph('Bangalore','Kozhikode',356,cities)
create_route_graph('Chennai','Bangalore',346,cities)
create_route_graph('Nellore','Chennai',175,cities)
create_route_graph('Mangalore','Kozhikode',233,cities)

In [93]:
print(adjacency_matrix)

[[  0 457 365 409   0   0   0   0   0   0]
 [457   0   0   0 453 100   0   0   0   0]
 [365   0   0   0   0   0 233 352   0   0]
 [409   0   0   0 379   0   0 311   0   0]
 [  0 453   0 379   0 340   0   0 136 153]
 [  0 100   0   0 340   0   0   0 325   0]
 [  0   0 233   0   0   0   0 356   0   0]
 [  0   0 352 311   0   0 356   0   0 346]
 [  0   0   0   0 136 325   0   0   0 175]
 [  0   0   0   0 153   0   0 346 175   0]]
